apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: redis
  name: vop-redis-pvc1
  labels:
    app: vop-redis-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 512Mi
  volumeName: vop-redis-pv1 # 如果pv未通过claimRef预留pvc，则可以直接绑定
#  selector:
#    matchExpressions:
#      - key: psm
#        operator: In
#        values:
#          - toutiao.videoarch.redis


