apiVersion: v1
kind: ConfigMap
metadata:
  name: twemproxy-config
  namespace: redis
  labels:
    app: twemproxy-config
data:
  twemproxy-redis.yaml: |
    slaves:
      listen: 0.0.0.0:22121
      hash: murmur
      distribution: ketama
      auto_eject_hosts: true
      redis_auth: 123456
      redis: true
      server_connections: 1
      server_retry_timeout: 30000
      timeout: 4000
      server_failure_limit: 3
      preconnect: true
      servers:
        - statefulset-default-toutiao-videoarch-redis-1.redis.redis.svc.cluster.local:6379:1
        - statefulset-default-toutiao-videoarch-redis-2.redis.redis.svc.cluster.local:6379:1
    master:
      listen: 0.0.0.0:22122
      hash: murmur
      distribution: ketama
      auto_eject_hosts: true
      redis_auth: 123456
      redis: true
      server_connections: 1
      server_retry_timeout: 30000
      timeout: 4000
      server_failure_limit: 3
      preconnect: true
      servers:
        - statefulset-default-toutiao-videoarch-redis-0.redis.redis.svc.cluster.local:6379:1
        
